# config/services.yaml

services:
  App\Services\CategoryService:
    arguments:
      $categoryRepository: '@App\Repository\CategoryRepository'
  App\Entity\Paint:
  # Configuration de votre entité Paint
parameters:

  upload_directory: '%kernel.project_dir%/public/uploads/images/'