vich_uploader:
    db_driver: orm

    metadata:
        type: attribute

    mappings:
        paint_image_file: # Nouveau mapping pour le champ "paintImageFile"
           uri_prefix: /uploads/images/paint/
           upload_destination: '%upload_directory%/paint'
           namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
           inject_on_load: false
           delete_on_update: true
           delete_on_remove: true
        inspiration_file: # Nouveau mapping pour le champ "inspirationFile"
           uri_prefix: /uploads/images/inspiration/
           upload_destination: '%upload_directory%/inspiration'
           namer: Vich\UploaderBundle\Naming\SmartUniqueNamer